apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.global.host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /users(/|$)(.*)
            backend:
              service:
                name: user-service
                port:
                  number: {{ .Values.global.ports.user }}
          - pathType: ImplementationSpecific
            path: /products(/|$)(.*)
            backend:
              service:
                name: warehouse-service
                port:
                  number: {{ .Values.global.ports.warehouse }}
          - pathType: ImplementationSpecific
            path: /orders(/|$)(.*)
            backend:
              service:
                name: order-service
                port:
                  number: {{ .Values.global.ports.order }}
          - pathType: ImplementationSpecific
            path: /purchase(/|$)(.*)
            backend:
              service:
                name: orchestrator-service
                port:
                  number: {{ .Values.global.ports.orchestrator }}
          - pathType: ImplementationSpecific
            path: /api(/|$)(.*)
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.global.ports.api }}
