apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /users(/|$)(.*)
            backend:
              service:
                name: {{ .Values.api.user.host }}
                port:
                  number: {{ .Values.api.user.port }}
          - pathType: ImplementationSpecific
            path: /products(/|$)(.*)
            backend:
              service:
                name: {{ .Values.api.warehouse.host }}
                port:
                  number: {{ .Values.api.warehouse.port }}
          - pathType: ImplementationSpecific
            path: /orders(/|$)(.*)
            backend:
              service:
                name: {{ .Values.api.order.host }}
                port:
                  number: {{ .Values.api.order.port }}
          - pathType: ImplementationSpecific
            path: /purchase(/|$)(.*)
            backend:
              service:
                name: {{ .Values.api.orchestrator.host }}
                port:
                  number: {{ .Values.api.orchestrator.port }}
          - pathType: ImplementationSpecific
            path: /api(/|$)(.*)
            backend:
              service:
                name: {{ .Values.api.host }}
                port:
                  number: {{ .Values.api.port }}
