apiVersion: v1
kind: Service
metadata:
    name: {{ .Chart.Name }}-service
spec:
  selector: 
    app: {{ .Chart.Name }}
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.global.port }}
    targetPort: {{ .Values.global.port }}
    protocol: TCP
