apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: basmingo/{{ .Chart.Name }}:latest
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.global.port }}
          env:
            - name: routers.orders.host
              value: {{ .Values.global.service.host.order }}
            - name: routers.orders.grpc-port
              value: {{ .Values.global.service.port.order }}
            - name: routers.warehouse.host
              value: {{ .Values.global.service.host.warehouse }}
            - name: routers.warehouse.grpc-port
              value: {{ .Values.global.service.port.warehouse }}
            - name: routers.users.host
              value: {{ .Values.global.service.host.user }}
            - name: routers.users.grpc-port
              value: {{ .Values.global.service.port.user }}
            - name: routers.orchestrator.host
              value: {{ .Values.global.service.host.orchestrator }}
            - name: routers.orchestrator.grpc-port
              value: {{ .Values.global.service.port.orchestrator }}
