apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: bitnami/kafka:latest
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.port.kafka.external }}
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:{{ .Values.port.zookeeper }}"
            - name: KAFKA_LISTENERS
              value: "EXTERNAL_SAME_HOST://:{{ .Values.port.kafka.external }},INTERNAL://:{{ .Values.port.kafka.internal }}"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka:{{ .Values.port.kafka.internal }},EXTERNAL_SAME_HOST://localhost:{{ .Values.port.kafka.external }}"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
