apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port.zookeeper }}
      targetPort: {{ .Values.port.zookeeper }}
      protocol: TCP
