apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: basmingo/{{ .Chart.Name }}:latest
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: temporal.enabled
              value: "{{ .Values.temporal.enabled }}"
            - name: temporal.host
              value: {{ .Values.temporal.host }}
