apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.global.name }}
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
    spec:
      containers:
        - image: {{ .Values.image.full }}
          name: {{ .Values.global.name }}
          ports:
            - containerPort: {{ .Values.global.port }}
