apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.global.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - image: bitnami/zookeeper:latest
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.port.zookeeper }}
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
