apiVersion: v2
appVersion: 1.16.0
description: A Helm chart for Kubernetes
name: api
type: application
version: 0.1.6
dependencies:
  - name: order
    version: 0.1.4
  - name: warehouse
    version: 0.1.4
  - name: user
    version: 0.1.4
  - name: kafka
    version: 0.1.4
  - name: orchestrator
    version: 0.1.4
